#!/bin/bash
set -e

if [ $# -lt 1 -o $# -gt 1 ]
then
    echo 'Usage: docker run --rm -v ${PWD}:/src pdidevel/deb_builder <obs_repodata.tar>' >&2
    exit 1
fi

RUNDIR="$PWD"

cd "$(mktemp -d --tmpdir LOCAL.XXXXXXXXXXXX.tmdir || exit 1)"
WKDIR="${PWD}"
trap "cd '${RUNDIR}'; rm -rf '${WKDIR}'" EXIT

cd "${RUNDIR}"
tar -C "${WKDIR}" -xf "$1"

cd "${WKDIR}"
apt-get update -qq
mk-build-deps -r -t "apt-get -y --no-install-recommends -qq" -i *.dsc
dpkg-source -x *.dsc
cd "$(find . -maxdepth 1 -type d -name '*-*')"
dpkg-buildpackage --no-sign

cd "${WKDIR}"
chown $(stat -c '%u:%g' "${RUNDIR}") *.deb *.dsc *.debian.tar.* *.orig.tar.*
mv *.deb *.dsc *.debian.tar.* *.orig.tar.* "${RUNDIR}"/
