#!/bin/bash
set -e

if [ $# -lt 1 -o $# -gt 1 ]
then
    echo 'Usage: docker run --rm -v ${PWD}:/src pdidevel/rpm_builder <obs_repodata.tar>' >&2
    exit 1
fi

RUNDIR="$PWD"

cd "$(mktemp -d --tmpdir LOCAL.XXXXXXXXXXXX.tmdir || exit 1)"
WKDIR="${PWD}"
trap "cd '${RUNDIR}'; rm -rf '${WKDIR}'" EXIT

cd "${RUNDIR}"
tar -C "${WKDIR}" -xf "$1"

cd "${WKDIR}"
yum-builddep -y *.spec
rpmbuild --define "_rpmdir ${WKDIR}" --define "_srcrpmdir ${WKDIR}" --undefine=_disable_source_fetch -ba *.spec
find . -name '*.rpm' -execdir chown "$(stat -c '%u:%g' "${RUNDIR}")" '{}' '+' 
find . -name '*.rpm' -execdir mv '{}' "${RUNDIR}" ';'
