name: Debuntu images
on:
  schedule: [ { cron: "50 23 * * 0" } ] # run every Sunday 23h50
  push: { branches: [ main, 'v*' ] }
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  debuntu:
    strategy:
      fail-fast: false
      matrix:
        base: ['ubuntu/jammy', 'ubuntu/rolling', 'debian/oldstable', 'debian/unstable']
        mpi: ['openmpi', 'mpich']
        variant: ['mini', 'all', 'pdi']
    runs-on: ubuntu-latest
    steps:
    - name: Compute distro & version
      id: info
      run: |
        BASE="${{ matrix.base }}"
        echo "distro=${BASE%/*}" >> "${GITHUB_OUTPUT}"
        echo "distro_version=${BASE##*/}" >> "${GITHUB_OUTPUT}"
    - name: "Build and push"
      uses: pdidev/test_env/.github/actions/build@v3
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        path: debuntu/${{ matrix.variant }}
        image-name: ${{ matrix.base }}/${{ matrix.mpi }}/${{ matrix.variant }}
        build-args: |
          MPI=${{ matrix.mpi }}
          DISTRO=${{ steps.info.outputs.distro }}
          DISTRO_VERSION=${{ steps.info.outputs.distro_version }}
    - name: Publish tagged
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
      run: |
        DOCKER_TAG="${{github.ref_name}}"
        docker tag \
          ghcr.io/pdidev/test_env/${{ matrix.base }}/${{ matrix.mpi }}/${{ matrix.variant }}:${GITHUB_SHA:0:7} \
          ghcr.io/pdidev/test_env/${{ matrix.base }}/${{ matrix.mpi }}/${{ matrix.variant }}:${{github.ref_name}}
        docker push ghcr.io/pdidev/test_env/${{ matrix.base }}/${{ matrix.mpi }}/${{ matrix.variant }}:${{github.ref_name}}
